version: '3.8'
services:
  task_manager:
    image: postgres:15
    restart: always
    ports:
      - '5434:5432'
    environment:
      POSTGRES_USER: nestuser
      POSTGRES_PASSWORD: nestpass
      POSTGRES_DB: taskdb
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
