name: NestJS CI/CD

on:
  push:
    branches: [main]

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install dependencies
      run: |
        cd task_backend_deploy
        npm install

    - name: Build backend app
      run: |
        cd task_backend_deploy
        npm run build

    # Burada deploy əlavə edə bilərsən
    # Məsələn, SSH ilə serverə kopyalamaq, Docker image yaratmaq və push etmək və s.
